### ISSUE TITLE
ni and sim

### ISSUE THREAD

**Issue by mojganzandi** [wxwmd/LPANNI#1]
How to calculate the node importance for weighted networks and
Also similarity between nodes for weighted networks in python

**Comment by mojganzandi** [comment]
Someone can help me that
How to calculate the node importance for weighted networks and
Also similarity between nodes for weighted networks in python

**Comment by wxwmd** [comment]
you are recommended to use the pagerank algorithm to compute the ni and the similarity between (u,v) is num(common neighbor of both (u,v))+1



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 13, 2021 16:58 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [wxwmd/LPANNI] ni and sim (#1)




 
Someone can help me that
 How to calculate the node importance for weighted networks and
 Also similarity between nodes for weighted networks in python
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mojganzandi** [comment]
can you help me to use PAGERANK to compute in NI and Similarity betwen nodes for weighted dataset 
for example my data is:
1    2     0.9
1    3     0.8
2    3      1

**Comment by mojganzandi** [comment]
in this code how use  page rank ?

def compute_NI(g: nx.Graph):
    max_ni = 0
    min_ni = 2 * g.number_of_nodes()
    for node in g.nodes:
        neighbors = list(g.adj[node].keys())
        triangle_num = 0
        for i in neighbors:
            for j in neighbors:
                if i < j and g.has_edge(i, j):
                    triangle_num += 1
        ni = g.degree[node] + triangle_num
        g.nodes[node]['NI'] = ni
        max_ni = max(max_ni, ni)
        min_ni = min(min_ni, ni)
    for node in g.nodes:
        g.nodes[node]['NI'] = 0.5 + 0.5 * (g.nodes[node]['NI'] - min_ni) / (max_ni - min_ni)


def compute_sim(g: nx.Graph):
    for edge in g.edges:
        u, v = edge[0], edge[1]
        # p=1
        s = 1.
        for i in list(g.adj[u].keys()):
            if g.has_edge(i, v):
                s += 1 / 2
        for i in list(g.adj[u].keys()):
            for j in list(g.adj[i].keys()):
                if g.has_edge(j, v) and (not j == u):
                    s += 1 / 3
        for i in (u, v):
            if g.nodes[i].get('s', -1) == -1:
                g.nodes[i]['s'] = {}
        g.nodes[u]['s'][v] = s
        g.nodes[v]['s'][u] = s
    for edge in g.edges:
        u, v = edge[0], edge[1]
        for i in (u, v):
            if g.nodes[i].get('sim', -1) == -1:
                g.nodes[i]['sim'] = {}
        sim = g.nodes[u]['s'][v] / (sum(g.nodes[u]['s'].values()) * sum(g.nodes[v]['s'].values())) ** 0.5
        g.nodes[u]['sim'][v] = sim
        g.nodes[v]['sim'][u] = sim
